{% set version = "0.9.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ssh
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ssh_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ssh/ssh_{{ version }}.tar.gz
  sha256: dbe313d597494f8941f9055ab2506ec0e3df0b5ed83f0aa9243a4e00e9a78a1a

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-askpass
    - r-credentials
    - libssh                       # [not win]
  run:
    - r-base
    - r-askpass
    - r-credentials

test:
  requires:
    - git                           # [win]
  commands:
    - $R -e "library('ssh')"           # [not win]
    - "\"%R%\" -e \"library('ssh')\""  # [win]

about:
  home: https://ropensci.r-universe.dev/ssh
  dev_url: https://github.com/ropensci/ssh
  doc_url: https://docs.ropensci.org/ssh
  license: MIT
  summary: Connect to a remote server over SSH to transfer files via SCP, setup a secure tunnel, or run a command or script on the host while streaming stdout and stderr directly to the client.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - lc5415
